### PR TITLE
add i18n

### PR DESCRIPTION
**Pull request by buiawpkgew1**

### CODE REVIEW

**Comment by afkvido** [comment]
Hold on. Most of your language packs are english even when they say that they aren't.

**Comment by buiawpkgew1** [comment]
It's translated by Crowdin, and there's no way for anyone in other languages to join.

**Comment by afkvido** [comment]
Screenshot 2022-11-11 at 12 09 30 AM

Then perhaps the languages that weren't translated shouldn't be included as a language pack.

Take a look at that image for example. It's supposed to be the language pack for the Russian language, but is still in English. For starters, I can help you with the Russian translation.

**Comment by buiawpkgew1** [comment]
This is convenient for translation.

**Comment by afkvido** [comment]
Alright, bet. Should I submit a thing on your Crowdin page, or can I just send you the translation here?

**Comment by buiawpkgew1** [comment]
It will automatically add branches and then pr.

**Comment by afkvido** [comment]
Sounds good to me- I'll send stuff to your Crowdin.

**Comment by buiawpkgew1** [comment]
ok

**Comment by udu3324** [comment]
Thank you for contributing! I looked over some of the commits and they are very good. I've never used crowdin before, so this is very new to me.

If you are adding Cowdin for the RegEx, make sure its exactly from Hypixel

**Comment by afkvido** [comment]
> If you are adding Cowdin for the RegEx, make sure its exactly from Hypixel

Yeah, that's one of the things. I need to know the RegEx for `/api new` for Russian, because I can't log on to Hypixel right now. If anyone could please send me it, thank you. I might finish the translation this week, but I am pretty busy.

**Comment by afkvido** [comment]
> Also, how will the user be able to switch between languages?

I'm pretty sure the Hytools language changes with the Minecraft language.

**Comment by udu3324** [comment]
> > Also, how will the user be able to switch between languages?
> 
> I'm pretty sure the Hytools language changes with the Minecraft language.

Oh okay, lmk when this pull request is ready to merge

**Comment by udu3324** [comment]
@buiawpkgew1 How do I add more strings to Crowdin and edit all of them at once?

**Comment by buiawpkgew1** [comment]
@udu3324 You can modify the one on GitHub because it is synchronized.

**Comment by buiawpkgew1** [comment]
image

**Comment by buiawpkgew1** [comment]
image
I'm so annoyed.

**Comment by buiawpkgew1** [comment]
@udu3324

**Comment by udu3324** [comment]
> image I'm so annoyed.

Hello, I am not sure why that is happening. When I run gradle build task, I do not get that error.

**Comment by buiawpkgew1** [comment]
> > image I'm so annoyed.
> 
> Hello, I am not sure why that is happening. When I run gradle build task, I do not get that error.

I don't know. It's fixed now.

**Comment by udu3324** [comment]
> > > image I'm so annoyed.
> > 
> > 
> > Hello, I am not sure why that is happening. When I run gradle build task, I do not get that error.
> 
> I don't know. It's fixed now.

This is very strange. Let me know if anything else is wrong though, I'll try to help

**Comment by buiawpkgew1** [comment]
> > > > image I'm so annoyed.
> > > 
> > > 
> > > Hello, I am not sure why that is happening. When I run gradle build task, I do not get that error.
> > 
> > 
> > I don't know. It's fixed now.
> 
> This is very strange. Let me know if anything else is wrong though, I'll try to help

I have added your Discord.

**Pull request merged**
